// <auto-generated />
using Gts.AuthorizationServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gts.AuthorizationServer.Migrations.ClaimDb
{
    [DbContext(typeof(ClaimDbContext))]
    [Migration("20231031175527_InitClaims")]
    partial class InitClaims
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gts.AuthorizationServer.Models.Users.ApplicationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApplicationClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "GetLoggingOperations"
                        },
                        new
                        {
                            Id = 2,
                            Name = "GetAllWarehouses"
                        },
                        new
                        {
                            Id = 3,
                            Name = "GetActiveWarehouses"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
