name: Deploy

on:
  push:
    branches:
      - master

env:
  SERVER_HOST: 54.39.207.182
  SERVER_USER: root
  SERVER_PATH: /root/src/TaskNinjaHub.AuthorizationServer/Gts.AuthorizationServer

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.

      # Install ssh key
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: "${{ secrets.AUTH_KEY }}"
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
          
      - name: Generate auth hosts
        run: ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts

      # Deploy
      - run: rsync --archive --compress --progress . ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH }}
      #Docker
      - name: Run Docker Compose
        run: ssh ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} "cd ${{ env.SERVER_PATH }} && docker-compose up -d --build"
